# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extension_store.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'extension_store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65xtension_store.proto\x12\x0fmihon.extension\"\x8b\x08\n\x15NetworkExtensionStore\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x62\x61\x64ge_label\x18\x02 \x01(\t\x12\x13\n\x0bsigning_key\x18\x03 \x01(\t\x12?\n\x07\x63ontact\x18\x04 \x01(\x0b\x32..mihon.extension.NetworkExtensionStore.Contact\x12L\n\x0e\x65xtension_list\x18\x65 \x01(\x0b\x32\x34.mihon.extension.NetworkExtensionStore.ExtensionList\x12\x1a\n\x12\x65xtension_list_url\x18\x66 \x01(\t\x1a<\n\x07\x43ontact\x12\x0f\n\x07website\x18\x01 \x01(\t\x12\x14\n\x07\x64iscord\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_discord\x1aU\n\rExtensionList\x12\x44\n\nextensions\x18\x01 \x03(\x0b\x32\x30.mihon.extension.NetworkExtensionStore.Extension\x1a\xc7\x02\n\tExtension\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cpackage_name\x18\x02 \x01(\t\x12\x43\n\tresources\x18\x03 \x01(\x0b\x32\x30.mihon.extension.NetworkExtensionStore.Resources\x12\x15\n\rextension_lib\x18\x04 \x01(\t\x12\x14\n\x0cversion_code\x18\x05 \x01(\x03\x12\x14\n\x0cversion_name\x18\x06 \x01(\t\x12N\n\x0f\x63ontent_warning\x18\x07 \x01(\x0e\x32\x35.mihon.extension.NetworkExtensionStore.ContentWarning\x12>\n\x07sources\x18\x08 \x03(\x0b\x32-.mihon.extension.NetworkExtensionStore.Source\x1a.\n\tResources\x12\x0f\n\x07\x61pk_url\x18\x01 \x01(\t\x12\x10\n\x08icon_url\x18\x02 \x01(\t\x1a}\n\x06Source\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x10\n\x08home_url\x18\x04 \x01(\t\x12\x13\n\x0bmirror_urls\x18\x05 \x03(\t\x12\x14\n\x07message\x18\x07 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"\x80\x01\n\x0e\x43ontentWarning\x12\x1f\n\x1b\x43ONTENT_WARNING_UNSPECIFIED\x10\x00\x12\x18\n\x14\x43ONTENT_WARNING_SAFE\x10\x01\x12\x19\n\x15\x43ONTENT_WARNING_MIXED\x10\x02\x12\x18\n\x14\x43ONTENT_WARNING_NSFW\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extension_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKEXTENSIONSTORE']._serialized_start=43
  _globals['_NETWORKEXTENSIONSTORE']._serialized_end=1078
  _globals['_NETWORKEXTENSIONSTORE_CONTACT']._serialized_start=295
  _globals['_NETWORKEXTENSIONSTORE_CONTACT']._serialized_end=355
  _globals['_NETWORKEXTENSIONSTORE_EXTENSIONLIST']._serialized_start=357
  _globals['_NETWORKEXTENSIONSTORE_EXTENSIONLIST']._serialized_end=442
  _globals['_NETWORKEXTENSIONSTORE_EXTENSION']._serialized_start=445
  _globals['_NETWORKEXTENSIONSTORE_EXTENSION']._serialized_end=772
  _globals['_NETWORKEXTENSIONSTORE_RESOURCES']._serialized_start=774
  _globals['_NETWORKEXTENSIONSTORE_RESOURCES']._serialized_end=820
  _globals['_NETWORKEXTENSIONSTORE_SOURCE']._serialized_start=822
  _globals['_NETWORKEXTENSIONSTORE_SOURCE']._serialized_end=947
  _globals['_NETWORKEXTENSIONSTORE_CONTENTWARNING']._serialized_start=950
  _globals['_NETWORKEXTENSIONSTORE_CONTENTWARNING']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
